development:
    dialect: mysql
    datasource: ${DSN}&parseTime=true
    dir: migrations

production:
    dialect: mysql
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST})/${MYSQL_DATABASE}?tls=true&parseTime=true
    dir: migrations
